package Controler;

import java.util.ArrayList;

import Auxiliar.Posicao;
import Modelo.*;

public class Fase extends ArrayList<Elemento> {
    public Fase(int iSize) {
        super(iSize);
    }

    public void setFase1(Hero umHero) {
        this.clear();
        this.add(umHero);
        umHero.setPosicao(4, 4);
        this.add(new QuadradoVermelho(new Posicao(1, 1)));
        this.add(new QuadradoVermelho(new Posicao(1, 3)));
        this.add(new QuadradoVermelho(new Posicao(1, 5)));
        this.add(new QuadradoVermelho(new Posicao(1, 7)));
        this.add(new QuadradoVermelho(new Posicao(1, 9)));
        this.add(new QuadradoVermelho(new Posicao(3, 1)));
        this.add(new QuadradoVermelho(new Posicao(3, 3)));
        this.add(new QuadradoVermelho(new Posicao(3, 5)));
        this.add(new QuadradoVermelho(new Posicao(3, 7)));
        this.add(new QuadradoVermelho(new Posicao(3, 9)));
        this.add(new QuadradoVermelho(new Posicao(5, 1)));
        this.add(new QuadradoVermelho(new Posicao(5, 3)));
        this.add(new QuadradoVermelho(new Posicao(5, 5)));
        this.add(new QuadradoVermelho(new Posicao(5, 7)));
        this.add(new QuadradoVermelho(new Posicao(5, 9)));
        this.add(new QuadradoVermelho(new Posicao(7, 1)));
        this.add(new QuadradoVermelho(new Posicao(7, 3)));
        this.add(new QuadradoVermelho(new Posicao(7, 5)));
        this.add(new QuadradoVermelho(new Posicao(7, 7)));
        this.add(new QuadradoVermelho(new Posicao(7, 9)));
        this.add(new QuadradoVermelho(new Posicao(9, 1)));
        this.add(new QuadradoVermelho(new Posicao(9, 3)));
        this.add(new QuadradoVermelho(new Posicao(9, 5)));
        this.add(new QuadradoVermelho(new Posicao(9, 7)));
        this.add(new QuadradoVermelho(new Posicao(9, 9)));
        this.add(new Coletavel("uva.png", new Posicao(0, 0)));
        this.add(new Coletavel("limao.png", new Posicao(0, 10)));
        this.add(new Coletavel("morango.png", new Posicao(10, 0)));
        this.add(new Coletavel("cereja.png", new Posicao(10, 10)));
        this.add(new Robo("roboAmarelo.png", new Posicao(2, 0)));
        this.add(new Robo("roboAzul.png", new Posicao(10, 1)));
        this.add(new Robo("roboRosa.png", new Posicao(0, 9)));
        this.add(new Robo("roboVerde.png", new Posicao(10, 9)));
        this.add(new QuadradoVerdeLosango(new Posicao(0, 1)));
        this.add(new QuadradoVerdeLosango(new Posicao(0, 5)));
        this.add(new QuadradoVerdeLosango(new Posicao(1, 2)));
        this.add(new QuadradoVerdeLosango(new Posicao(1, 8)));
        this.add(new QuadradoVerdeLosango(new Posicao(1, 10)));
        this.add(new QuadradoVerdeLosango(new Posicao(2, 1)));
        this.add(new QuadradoVerdeLosango(new Posicao(2, 6)));
        this.add(new QuadradoVerdeLosango(new Posicao(3, 0)));
        this.add(new QuadradoVerdeLosango(new Posicao(3, 8)));
        this.add(new QuadradoVerdeLosango(new Posicao(4, 1)));
        this.add(new QuadradoVerdeLosango(new Posicao(4, 9)));
        this.add(new QuadradoVerdeLosango(new Posicao(5, 2)));
        this.add(new QuadradoVerdeLosango(new Posicao(5, 6)));
        this.add(new QuadradoVerdeLosango(new Posicao(6, 5)));
        this.add(new QuadradoVerdeLosango(new Posicao(6, 7)));
        this.add(new QuadradoVerdeLosango(new Posicao(7, 8)));
        this.add(new QuadradoVerdeLosango(new Posicao(7, 10)));
        this.add(new QuadradoVerdeLosango(new Posicao(8, 3)));
        this.add(new QuadradoVerdeLosango(new Posicao(8, 9)));
        this.add(new QuadradoVerdeLosango(new Posicao(9, 0)));
        this.add(new QuadradoVerdeLosango(new Posicao(9, 2)));
        this.add(new QuadradoVerdeLosango(new Posicao(9, 6)));
        this.add(new QuadradoVerdeLosango(new Posicao(9, 8)));
        this.add(new QuadradoVerdeLosango(new Posicao(10, 7)));
    }

    public void setFase2(Hero umHero) {
        this.clear();
        this.add(umHero);
        umHero.setPosicao(5, 5);
        this.add(new EsteiraCima(new Posicao(3, 0)));
        this.add(new EsteiraCima(new Posicao(3, 6)));
        this.add(new EsteiraCima(new Posicao(3, 8)));
        this.add(new EsteiraCima(new Posicao(4, 0)));
        this.add(new EsteiraCima(new Posicao(4, 8)));
        this.add(new EsteiraCima(new Posicao(5, 0)));
        this.add(new EsteiraCima(new Posicao(6, 0)));
        this.add(new EsteiraCima(new Posicao(7, 0)));
        this.add(new EsteiraCima(new Posicao(7, 6)));
        this.add(new EsteiraCima(new Posicao(7, 8)));
        this.add(new EsteiraCima(new Posicao(7, 10)));
        this.add(new EsteiraDireita(new Posicao(0, 3)));
        this.add(new EsteiraDireita(new Posicao(0, 7)));
        this.add(new EsteiraDireita(new Posicao(2, 3)));
        this.add(new EsteiraDireita(new Posicao(4, 3)));
        this.add(new EsteiraDireita(new Posicao(4, 7)));
        this.add(new EsteiraDireita(new Posicao(6, 3)));
        this.add(new EsteiraDireita(new Posicao(8, 3)));
        this.add(new EsteiraDireita(new Posicao(8, 7)));
        this.add(new EsteiraDireita(new Posicao(10, 7)));
        this.add(new EsteiraEsquerda(new Posicao(2, 5)));
        this.add(new EsteiraEsquerda(new Posicao(2, 6)));
        this.add(new EsteiraEsquerda(new Posicao(2, 7)));
        this.add(new EsteiraEsquerda(new Posicao(4, 9)));
        this.add(new EsteiraEsquerda(new Posicao(4, 10)));
        this.add(new EsteiraEsquerda(new Posicao(6, 7)));
        this.add(new EsteiraEsquerda(new Posicao(10, 3)));
        this.add(new EsteiraBaixo(new Posicao(2, 4)));
        this.add(new EsteiraBaixo(new Posicao(3, 2)));
        this.add(new EsteiraBaixo(new Posicao(3, 4)));
        this.add(new EsteiraBaixo(new Posicao(3, 10)));
        this.add(new EsteiraBaixo(new Posicao(7, 2)));
        this.add(new EsteiraBaixo(new Posicao(7, 4)));
        this.add(new QuadradoVermelho(new Posicao(1, 3)));
        this.add(new QuadradoVermelho(new Posicao(1, 7)));
        this.add(new QuadradoVermelho(new Posicao(3, 1)));
        this.add(new QuadradoVermelho(new Posicao(3, 3)));
        this.add(new QuadradoVermelho(new Posicao(3, 5)));
        this.add(new QuadradoVermelho(new Posicao(3, 7)));
        this.add(new QuadradoVermelho(new Posicao(3, 9)));
        this.add(new QuadradoVermelho(new Posicao(5, 3)));
        this.add(new QuadradoVermelho(new Posicao(5, 7)));
        this.add(new QuadradoVermelho(new Posicao(7, 1)));
        this.add(new QuadradoVermelho(new Posicao(7, 3)));
        this.add(new QuadradoVermelho(new Posicao(7, 5)));
        this.add(new QuadradoVermelho(new Posicao(7, 7)));
        this.add(new QuadradoVermelho(new Posicao(7, 9)));
        this.add(new QuadradoVermelho(new Posicao(9, 3)));
        this.add(new QuadradoVermelho(new Posicao(9, 7)));
        this.add(new Robo("roboAmarelo.png", new Posicao(1, 1)));
        this.add(new Robo("roboAzul.png", new Posicao(9, 9)));
        this.add(new Robo("roboRosa.png", new Posicao(9, 1)));
        this.add(new Robo("roboVerde.png", new Posicao(1, 9)));
        this.add(new Coletavel("uva.png", new Posicao(1, 5)));
        this.add(new Coletavel("limao.png", new Posicao(5, 1)));
        this.add(new Coletavel("morango.png", new Posicao(5, 9)));
        this.add(new Coletavel("cereja.png", new Posicao(9, 5)));
    }

    public void setFase3(Hero umHero) {
        this.clear();
        this.add(umHero);
        umHero.setPosicao(5, 5);
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 2)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 3)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 4)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 5)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 6)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 7)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 8)));
        this.add(new QuadradoVermelhoLosango(new Posicao(1, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(2, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(2, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(3, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(3, 3)));
        this.add(new QuadradoVermelhoLosango(new Posicao(3, 4)));
        this.add(new QuadradoVermelhoLosango(new Posicao(3, 5)));
        this.add(new QuadradoVermelhoLosango(new Posicao(3, 6)));
        this.add(new QuadradoVermelhoLosango(new Posicao(3, 7)));
        this.add(new QuadradoVermelhoLosango(new Posicao(3, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(4, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(4, 3)));
        this.add(new QuadradoVermelhoLosango(new Posicao(4, 7)));
        this.add(new QuadradoVermelhoLosango(new Posicao(4, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(5, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(5, 3)));
        this.add(new QuadradoVermelhoLosango(new Posicao(5, 7)));
        this.add(new QuadradoVermelhoLosango(new Posicao(5, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(6, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(6, 3)));
        this.add(new QuadradoVermelhoLosango(new Posicao(6, 7)));
        this.add(new QuadradoVermelhoLosango(new Posicao(6, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(7, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(7, 3)));
        this.add(new QuadradoVermelhoLosango(new Posicao(7, 4)));
        this.add(new QuadradoVermelhoLosango(new Posicao(7, 5)));
        this.add(new QuadradoVermelhoLosango(new Posicao(7, 6)));
        this.add(new QuadradoVermelhoLosango(new Posicao(7, 7)));
        this.add(new QuadradoVermelhoLosango(new Posicao(7, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(8, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(8, 9)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 1)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 2)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 3)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 4)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 5)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 6)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 7)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 8)));
        this.add(new QuadradoVermelhoLosango(new Posicao(9, 9)));
        this.add(new Robo("roboAmarelo.png", new Posicao(0, 5)));
        this.add(new Robo("roboAzul.png", new Posicao(8, 5)));
        this.add(new Robo("roboRosa.png", new Posicao(2, 5)));
        this.add(new Robo("roboVerde.png", new Posicao(10, 5)));
        this.add(new Coletavel("uva.png", new Posicao(5, 0)));
        this.add(new Coletavel("limao.png", new Posicao(5, 2)));
        this.add(new Coletavel("morango.png", new Posicao(5, 8)));
        this.add(new Coletavel("cereja.png", new Posicao(5, 10)));
    }

    public void setFase4(Hero umHero) {
        this.clear();
        this.add(umHero);
        umHero.setPosicao(4, 5);
        this.add(new QuadradoVermelho(new Posicao(0, 3)));
        this.add(new QuadradoVermelho(new Posicao(0, 7)));
        this.add(new QuadradoVermelho(new Posicao(1, 0)));
        this.add(new QuadradoVermelho(new Posicao(1, 8)));
        this.add(new QuadradoVermelho(new Posicao(2, 5)));
        this.add(new QuadradoVermelho(new Posicao(3, 2)));
        this.add(new QuadradoVermelho(new Posicao(3, 10)));
        this.add(new QuadradoVermelho(new Posicao(5, 2)));
        this.add(new QuadradoVermelho(new Posicao(5, 8)));
        this.add(new QuadradoVermelho(new Posicao(6, 3)));
        this.add(new QuadradoVermelho(new Posicao(7, 0)));
        this.add(new QuadradoVermelho(new Posicao(8, 1)));
        this.add(new QuadradoVermelho(new Posicao(8, 7)));
        this.add(new QuadradoVermelho(new Posicao(8, 10)));
        this.add(new QuadradoVermelho(new Posicao(10, 1)));
        this.add(new QuadradoVerde(new Posicao(1, 1)));
        this.add(new QuadradoVerde(new Posicao(1, 3)));
        this.add(new QuadradoVerde(new Posicao(1, 5)));
        this.add(new QuadradoVerde(new Posicao(1, 7)));
        this.add(new QuadradoVerde(new Posicao(1, 9)));
        this.add(new QuadradoVerde(new Posicao(2, 2)));
        this.add(new QuadradoVerde(new Posicao(2, 4)));
        this.add(new QuadradoVerde(new Posicao(2, 6)));
        this.add(new QuadradoVerde(new Posicao(2, 8)));
        this.add(new QuadradoVerde(new Posicao(3, 1)));
        this.add(new QuadradoVerde(new Posicao(3, 3)));
        this.add(new QuadradoVerde(new Posicao(3, 5)));
        this.add(new QuadradoVerde(new Posicao(3, 7)));
        this.add(new QuadradoVerde(new Posicao(3, 9)));
        this.add(new QuadradoVerde(new Posicao(4, 2)));
        this.add(new QuadradoVerde(new Posicao(4, 4)));
        this.add(new QuadradoVerde(new Posicao(4, 6)));
        this.add(new QuadradoVerde(new Posicao(4, 8)));
        this.add(new QuadradoVerde(new Posicao(5, 1)));
        this.add(new QuadradoVerde(new Posicao(5, 3)));
        this.add(new QuadradoVerde(new Posicao(5, 5)));
        this.add(new QuadradoVerde(new Posicao(5, 7)));
        this.add(new QuadradoVerde(new Posicao(5, 9)));
        this.add(new QuadradoVerde(new Posicao(6, 2)));
        this.add(new QuadradoVerde(new Posicao(6, 4)));
        this.add(new QuadradoVerde(new Posicao(6, 6)));
        this.add(new QuadradoVerde(new Posicao(6, 8)));
        this.add(new QuadradoVerde(new Posicao(7, 1)));
        this.add(new QuadradoVerde(new Posicao(7, 3)));
        this.add(new QuadradoVerde(new Posicao(7, 5)));
        this.add(new QuadradoVerde(new Posicao(7, 7)));
        this.add(new QuadradoVerde(new Posicao(7, 9)));
        this.add(new QuadradoVerde(new Posicao(8, 2)));
        this.add(new QuadradoVerde(new Posicao(8, 4)));
        this.add(new QuadradoVerde(new Posicao(8, 6)));
        this.add(new QuadradoVerde(new Posicao(8, 8)));
        this.add(new QuadradoVerde(new Posicao(9, 1)));
        this.add(new QuadradoVerde(new Posicao(9, 3)));
        this.add(new QuadradoVerde(new Posicao(9, 5)));
        this.add(new QuadradoVerde(new Posicao(9, 7)));
        this.add(new QuadradoVerde(new Posicao(9, 9)));
        this.add(new Robo("roboAmarelo.png", new Posicao(0, 5)));
        this.add(new Robo("roboAzul.png", new Posicao(5, 10)));
        this.add(new Robo("roboRosa.png", new Posicao(10, 5)));
        this.add(new Robo("roboVerde.png", new Posicao(5, 0)));
        this.add(new Coletavel("uva.png", new Posicao(0, 0)));
        this.add(new Coletavel("limao.png", new Posicao(0, 10)));
        this.add(new Coletavel("morango.png", new Posicao(10, 0)));
        this.add(new Coletavel("cereja.png", new Posicao(10, 10)));
    }
}
